version: '2'
services:
    stagecapservice-app:
        image: stagecapservice
        external_links:
            - stagecapservice-mysql:mysql
            - stagecapservice-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stagecapservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    stagecapservice-mysql:
        extends:
            file: mysql.yml
            service: stagecapservice-mysql
    stagecapservice-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: stagecapservice-elasticsearch
